#ifndef LOADING_H_
#define LOADING_H_

#include "../output/output.h"

#define LOADING_DOTS_OFFSET  (BOARD_HEIGHT - 10) / 2
#define LOADING_DOTS         5,LOADING_DOTS_OFFSET, 6,LOADING_DOTS_OFFSET, 7,LOADING_DOTS_OFFSET+1, 8,LOADING_DOTS_OFFSET+2, 9,LOADING_DOTS_OFFSET+3, 9,LOADING_DOTS_OFFSET+4, \
                             9,LOADING_DOTS_OFFSET+5, 9,LOADING_DOTS_OFFSET+6, 8,LOADING_DOTS_OFFSET+7, 7,LOADING_DOTS_OFFSET+8, 6,LOADING_DOTS_OFFSET+9, 5,LOADING_DOTS_OFFSET+9, \
                             4,LOADING_DOTS_OFFSET+9, 3,LOADING_DOTS_OFFSET+9, 2,LOADING_DOTS_OFFSET+8, 1,LOADING_DOTS_OFFSET+7, 0,LOADING_DOTS_OFFSET+6, 0,LOADING_DOTS_OFFSET+5, \
                             0,LOADING_DOTS_OFFSET+4, 0,LOADING_DOTS_OFFSET+3, 1,LOADING_DOTS_OFFSET+2, 2,LOADING_DOTS_OFFSET+1, 3,LOADING_DOTS_OFFSET, 4,LOADING_DOTS_OFFSET
#define LOADING_DOT_COLOR    3
#define LOADING_DOT_DELAY    50

void            loading_main(void);

#endif				/* LOADING_H_ */
