dist: xenial
language: c

env:
  - CC=gcc
  - CC=clang
  - CC=x86_64-w64-mingw32-gcc-win32

before_install:
  - sudo apt-get update
  - sudo apt-get install -y make scons gcc-mingw-w64-x86-64

script: make
