dist: xenial
language: c

compiler:
  #- arm-linux-gnueabihf-gcc
  #- avr-gcc
  #- clang
  - gcc
  #- x86_64-w64-mingw32-gcc-win32

env:
  - CROSS_COMPILE=arm-linux-gnueabihf-
  - CROSS_COMPILE=avr-

before_install:
  - sudo apt-get update
  - sudo apt-get install -y make scons gcc-arm-linux-gnueabihf gcc-avr gcc-mingw-w64-x86-64

script: make
